### ISSUE TITLE
macOS: Internal Server Error when updating to 1.10.4

### ISSUE THREAD

**Issue by theforcedk** [cryptoadvance/specter-desktop#1815]
**Describe the bug**
On macOS Monterey -- upgrading from 1.10.3 to 1.10.4 causes the login screen to provide an Internal Server Error page.

**To Reproduce**
Download DMG from Github, replace existing application without uninstalling.

**Screenshots**
<img width="1608" alt="Screen Shot 2022-07-19 at 5 49 54 PM" src="https://user-images.githubusercontent.com/465579/179794340-000bfd30-7eeb-48bb-8a2b-8222fe023018.png">

**Logs**
```
2022-07-19T15:54:32.074Z [info] : stderr-SPECTERD: ERROR in version: get() missing 1 required positional argument: 'url'
Traceback (most recent call last):
  File "cryptoadvance/specter/util/version.py", line 162, in _get_latest_version_from_github
TypeError: get() missing 1 required positional argument: 'url'

2022-07-19T15:54:32.074Z [info] : stderr-SPECTERD: INFO in version: version checker stopped.
SPECTERD: INFO in version: version checked, install_type app curr: v1.10.4 latest: unknown ==> upgrade: False
<snip>
    <title>{{ _("Specter Desktop") }}</title>
  File "/var/folders/y5/_5b0dnl91ksg7hg3y8nw89xc0000gn/T/_MEIwqZCTi/jinja2/ext.py", line 167, in _gettext_alias
    
  File "/var/folders/y5/_5b0dnl91ksg7hg3y8nw89xc0000gn/T/_MEIwqZCTi/jinja2/ext.py", line 173, in gettext
    
  File "/var/folders/y5/_5b0dnl91ksg7hg3y8nw89xc0000gn/T/_MEIwqZCTi/cryptoadvance/specter/htmlsafebabel.py", line 19, in <lambda>
    
  File "/var/folders/y5/_5b0dnl91ksg7hg3y8nw89xc0000gn/T/_MEIwqZCTi/cryptoadvance/specter/htmlsafebabel.py", line 33, in reescape_string
    
AttributeError: 'HTMLParser' object has no attribute 'unescape'

2022-07-19T15:46:03.629Z [info] : stderr-SPECTERD: ERROR in controller: Uncaught exception: 'HTMLParser' object has no attribute 'unescape'

2022-07-19T15:46:03.629Z [info] : stderr-SPECTERD: ERROR in controller: Traceback (most recent call last):
  File "flask/app.py", line 1523, in full_dispatch_request
  File "flask/app.py", line 1509, in dispatch_request
  File "cryptoadvance/specter/server_endpoints/auth.py", line 100, in login
  File "flask/templating.py", line 148, in render_template
  File "flask/templating.py", line 128, in _render
  File "jinja2/environment.py", line 1291, in render
  File "jinja2/environment.py", line 926, in handle_exception
  File "/var/folders/y5/_5b0dnl91ksg7hg3y8nw89xc0000gn/T/_MEIwqZCTi/templates/login.jinja", line 1, in top-level template code
    {% extends "base.jinja" %}
  File "/var/folders/y5/_5b0dnl91ksg7hg3y8nw89xc0000gn/T/_MEIwqZCTi/templates/base.jinja", line 5, in top-level template code
    <title>{{ _("Specter Desktop") }}</title>
  File "jinja2/ext.py", line 167, in _gettext_alias
  File "jinja2/ext.py", line 173, in gettext
  File "cryptoadvance/specter/htmlsafebabel.py", line 19, in <lambda>
  File "cryptoadvance/specter/htmlsafebabel.py", line 33, in reescape_string
AttributeError: 'HTMLParser' object has no attribute 'unescape'


2022-07-19T15:46:03.630Z [info] : stderr-SPECTERD: ERROR in app: Exception on /auth/login [GET]
Traceback (most recent call last):
  File "flask/app.py", line 1523, in full_dispatch_request
  File "flask/app.py", line 1509, in dispatch_request
  File "cryptoadvance/specter/server_endpoints/auth.py", line 100, in login
  File "flask/templating.py", line 148, in render_template
  File "flask/templating.py", line 128, in _render
  File "jinja2/environment.py", line 1291, in render
  File "jinja2/environment.py", line 926, in handle_exception
  File "/var/folders/y5/_5b0dnl91ksg7hg3y8nw89xc0000gn/T/_MEIwqZCTi/templates/login.jinja", line 1, in top-level template code
    {% extends "base.jinja" %}
  File "/var/folders/y5/_5b0dnl91ksg7hg3y8nw89xc0000gn/T/_MEIwqZCTi/templates/base.jinja", line 5, in top-level template code
    <title>{{ _("Specter Desktop") }}</title>
  File "jinja2/ext.py", line 167, in _gettext_alias
  File "jinja2/ext.py", line 173, in gettext
  File "cryptoadvance/specter/htmlsafebabel.py", line 19, in <lambda>
  File "cryptoadvance/specter/htmlsafebabel.py", line 33, in reescape_string
AttributeError: 'HTMLParser' object has no attribute 'unescape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask/app.py", line 2077, in wsgi_app
  File "flask/app.py", line 1525, in full_dispatch_request
  File "flask/app.py", line 1391, in handle_user_exception
  File "cryptoadvance/specter/server_endpoints/controller.py", line 101, in server_error
  File "flask/templating.py", line 148, in render_template
  File "flask/templating.py", line 128, in _render
  File "jinja2/environment.py", line 1291, in render
  File "jinja2/environment.py", line 926, in handle_exception
  File "/var/folders/y5/_5b0dnl91ksg7hg3y8nw89xc0000gn/T/_MEIwqZCTi/templates/500.jinja", line 5, in top-level template code
    <title>{{ _("Specter Desktop") }}</title>
  File "jinja2/ext.py", line 167, in _gettext_alias
  File "jinja2/ext.py", line 173, in gettext
  File "cryptoadvance/specter/htmlsafebabel.py", line 19, in <lambda>
  File "cryptoadvance/specter/htmlsafebabel.py", line 33, in reescape_string
AttributeError: 'HTMLParser' object has no attribute 'unescape'

2022-07-19T15:46:03.638Z [info] : stderr-SPECTERD: ERROR in controller: Uncaught exception: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

2022-07-19T15:46:03.638Z [info] : stderr-SPECTERD: ERROR in controller: Traceback (most recent call last):
  File "flask/app.py", line 1523, in full_dispatch_request
  File "flask/app.py", line 1509, in dispatch_request
  File "cryptoadvance/specter/server_endpoints/auth.py", line 100, in login
  File "flask/templating.py", line 148, in render_template
  File "flask/templating.py", line 128, in _render
  File "jinja2/environment.py", line 1291, in render
  File "jinja2/environment.py", line 926, in handle_exception
  File "/var/folders/y5/_5b0dnl91ksg7hg3y8nw89xc0000gn/T/_MEIwqZCTi/templates/login.jinja", line 1, in top-level template code
    {% extends "base.jinja" %}
  File "/var/folders/y5/_5b0dnl91ksg7hg3y8nw89xc0000gn/T/_MEIwqZCTi/templates/base.jinja", line 5, in top-level template code
    <title>{{ _("Specter Desktop") }}</title>
  File "jinja2/ext.py", line 167, in _gettext_alias
  File "jinja2/ext.py", line 173, in gettext
  File "cryptoadvance/specter/htmlsafebabel.py", line 19, in <lambda>
  File "cryptoadvance/specter/htmlsafebabel.py", line 33, in reescape_string
AttributeError: 'HTMLParser' object has no attribute 'unescape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask/app.py", line 2077, in wsgi_app
  File "flask/app.py", line 1525, in full_dispatch_request
  File "flask/app.py", line 1391, in handle_user_exception
  File "cryptoadvance/specter/server_endpoints/controller.py", line 101, in server_error
  File "flask/templating.py", line 148, in render_template
  File "flask/templating.py", line 128, in _render
  File "jinja2/environment.py", line 1291, in render
  File "jinja2/environment.py", line 926, in handle_exception
  File "/var/folders/y5/_5b0dnl91ksg7hg3y8nw89xc0000gn/T/_MEIwqZCTi/templates/500.jinja", line 5, in top-level template code
    <title>{{ _("Specter Desktop") }}</title>
  File "jinja2/ext.py", line 167, in _gettext_alias
  File "jinja2/ext.py", line 173, in gettext
  File "cryptoadvance/specter/htmlsafebabel.py", line 19, in <lambda>
  File "cryptoadvance/specter/htmlsafebabel.py", line 33, in reescape_string
AttributeError: 'HTMLParser' object has no attribute 'unescape'


2022-07-19T15:46:03.641Z [info] : stderr-SPECTERD: INFO in _internal: 127.0.0.1 - - [19/Jul/2022 17:46:03] "[35m[1mGET /auth/login?next=%2Fwelcome%2F HTTP/1.1[0m" 500 -

2022-07-19T15:46:03.648Z [info] : stderr-SPECTERD: ERROR in _internal: Error on request:
Traceback (most recent call last):
  File "/var/folders/y5/_5b0dnl91ksg7hg3y8nw89xc0000gn/T/_MEIwqZCTi/flask/app.py", line 1523, in full_dispatch_request
    
  File "/var/folders/y5/_5b0dnl91ksg7hg3y8nw89xc0000gn/T/_MEIwqZCTi/flask/app.py", line 1509, in dispatch_request
    
  File "/var/folders/y5/_5b0dnl91ksg7hg3y8nw89xc0000gn/T/_MEIwqZCTi/cryptoadvance/specter/server_endpoints/auth.py", line 100, in login
    
  File "/var/folders/y5/_5b0dnl91ksg7hg3y8nw89xc0000gn/T/_MEIwqZCTi/flask/templating.py", line 148, in render_template
    
  File "/var/folders/y5/_5b0dnl91ksg7hg3y8nw89xc0000gn/T/_MEIwqZCTi/flask/templating.py", line 128, in _render
    
  File "/var/folders/y5/_5b0dnl91ksg7hg3y8nw89xc0000gn/T/_MEIwqZCTi/jinja2/environment.py", line 1291, in render
    
  File "/var/folders/y5/_5b0dnl91ksg7hg3y8nw89xc0000gn/T/_MEIwqZCTi/jinja2/environment.py", line 926, in handle_exception
    
  File "/private/var/folders/y5/_5b0dnl91ksg7hg3y8nw89xc0000gn/T/_MEIwqZCTi/templates/login.jinja", line 1, in top-level template code
    {% extends "base.jinja" %}
  File "/private/var/folders/y5/_5b0dnl91ksg7hg3y8nw89xc0000gn/T/_MEIwqZCTi/templates/base.jinja", line 5, in top-level template code
    <title>{{ _("Specter Desktop") }}</title>
  File "/var/folders/y5/_5b0dnl91ksg7hg3y8nw89xc0000gn/T/_MEIwqZCTi/jinja2/ext.py", line 167, in _gettext_alias
    
  File "/var/folders/y5/_5b0dnl91ksg7hg3y8nw89xc0000gn/T/_MEIwqZCTi/jinja2/ext.py", line 173, in gettext
    
  File "/var/folders/y5/_5b0dnl91ksg7hg3y8nw89xc0000gn/T/_MEIwqZCTi/cryptoadvance/specter/htmlsafebabel.py", line 19, in <lambda>
    
  File "/var/folders/y5/_5b0dnl91ksg7hg3y8nw89xc0000gn/T/_MEIwqZCTi/cryptoadvance/specter/htmlsafebabel.py", line 33, in reescape_string
    
AttributeError: 'HTMLParser' object has no attribute 'unescape'
<repeating messages>
```

**Comment by theforcedk** [comment]
Seems that launching a fresh installation (eg. removing ~/.specter) has the same issue.

**Comment by mariusb** [comment]
I just upgraded from 1.10.3 --> 1.10.4 and got the same error.
I reverted back to 1.10.3 and it is working fine so it is an issue with 1.10.4

**Comment by moneymanolis** [comment]
I can confirm the problems. This seems to be related to the latest PR #1793.

**Comment by k9ert** [comment]
Ok, this is fixed in `v1.10.5` which just got released:
https://github.com/cryptoadvance/specter-desktop/releases/tag/v1.10.5

**Comment by frankcastro** [comment]
Definitely working!  Thank you so much!
