### ISSUE TITLE
Error in display_address (regression from 1.8.1. to 1.10.2)

### ISSUE THREAD

**Issue by real-or-random** [cryptoadvance/specter-desktop#1760]
**Describe the bug**

When clicking "Display Address on Device" for bitbox02 in a multisig wallet 
```
2022-06-13T12:22:56.948Z [info] : stderr-Traceback (most recent call last):   
File "cryptoadvance/specter/util/json_rpc.py", line 35, in jsonrpc   
File "cryptoadvance/specter/helpers.py", line 81, in wrapper_fn   
File "cryptoadvance/specter/hwi_rpc.py", line 289, in display_address 
AttributeError: 'str' object has no attribute 'get'
```

**Desktop (please complete the following information):**
 - Where is your node running: local(external), 23.0
 - Where is your specter running: binary
 - If you're running a binary, which OS: Linux
 - Specter Version 1.10.2

**Additional context**

This appeared after upgrading to 1.10.2. It worked on Specter 1.8.1.

**Comment by k9ert** [comment]
Thank you very much. That's important to fix quickly.
The last line 289 looks like this:
```
if descriptor.get("xpubs_descriptor", None):
```
This is a rpc-call coming from the browser.
In `v1.9.4` that call looks like this:
![image](https://user-images.githubusercontent.com/117085/174398459-73ffe5d7-1639-41fa-8932-6a148a6816aa.png)
In `v1.10.0` it looks line this:
![image](https://user-images.githubusercontent.com/117085/174399034-ef4ceb77-6e10-4ad7-abc2-c5e10b0ef6ca.png)

So that bug was introduced in `v1.10.0`:
https://github.com/cryptoadvance/specter-desktop/releases/tag/v1.10.0

**Comment by k9ert** [comment]
@moneymanolis i can remember to have discussed even that exchange but can't remember the context. Please have a look!
