### ISSUE TITLE
v2.0.0 Install issue

### ISSUE THREAD

**Issue by sanyangGitHub** [cryptoadvance/specter-desktop#2314]
Hi!
Get an error message trying to upgrade to v2.0.0

_"ERROR: Could not find a version that satisfies the requirement cryptoadvance.spectrum==0.6.2 (from cryptoadvance-specter)
ERROR: No matching distribution found for cryptoadvance.spectrum==0.6.2"_

Can't find any support for this error.

Thanks for your help !

**Comment by BTCBellyButton** [comment]
Same.

**Comment by BTCBellyButton** [comment]
In my case upgrade via pip. No dev.

**Comment by sanyangGitHub** [comment]
same

`$ /tmp$ wget https://github.com/cryptoadvance/specter-desktop/releases/download/v2.0.0/cryptoadvance.specter-2.0.0.tar.gz
2023-03-23 21:33:03 (3.77 MB/s) - 'cryptoadvance.specter-2.0.0.tar.gz' saved [13655355/13655355]
$ /tmp$ wget https://github.com/cryptoadvance/specter-desktop/releases/download/v2.0.0/SHA256SUMS
2023-03-23 21:33:37 (63.0 MB/s) - 'SHA256SUMS' saved [668/668]
$ /tmp$ sha256sum --ignore-missing --check SHA256SUMS
cryptoadvance.specter-2.0.0.tar.gz: OK
$ /tmp$ wget https://github.com/cryptoadvance/specter-desktop/releases/download/v2.0.0/SHA256SUMS.asc
2023-03-23 21:34:12 (33.4 MB/s) - 'SHA256SUMS.asc' saved [833/833]
$ /tmp$ gpg --verify SHA256SUMS.asc
gpg: assuming signed data in 'SHA256SUMS'
gpg: Signature made Wed Mar  8 14:13:34 2023 UTC
gpg:                using RSA key 785A2269EE3A9736AC1A4F4C864B7CF9A811FEF7
gpg: Good signature from "Specter Signer <noreply@specter.solutions>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 785A 2269 EE3A 9736 AC1A  4F4C 864B 7CF9 A811 FEF7
$ /tmp$ tar -xvzf cryptoadvance.specter-2.0.0.tar.gz cryptoadvance.specter-2.0.0/requirements.txt
cryptoadvance.specter-2.0.0/requirements.txt
$ /tmp$ virtualenv --python=python3 .env
/home/ /.local/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
created virtual environment CPython3.9.2.final.0-64 in 126ms
  creator CPython3Posix(dest=/tmp/.env, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/admin/.local/share/virtualenv)
    added seed packages: pip==20.3.4, pkg_resources==0.0.0, setuptools==44.1.1, wheel==0.34.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
$ /tmp$ sudo pip3 install -r cryptoadvance.specter-2.0.0/requirements.txt --require-hashes --upgrade
Requirement already satisfied: aniso8601==9.0.1 in /usr/local/lib/python3.9/dist-packages (from -r cryptoadvance.specter-2.0.0/requirements.txt (line 7)) (9.0.1)
Collecting apscheduler==3.10.0
  Using cached APScheduler-3.10.0-py3-none-any.whl (59 kB)
Collecting babel==2.11.0
  Using cached Babel-2.11.0-py3-none-any.whl (9.5 MB)
Requirement already satisfied: base58==2.1.1 in /usr/local/lib/python3.9/dist-packages (from -r cryptoadvance.specter-2.0.0/requirements.txt (line 19)) (2.1.1)
Requirement already satisfied: bitbox02==6.1.1 in /usr/local/lib/python3.9/dist-packages (from -r cryptoadvance.specter-2.0.0/requirements.txt (line 23)) (6.1.1)
Requirement already satisfied: cbor==1.0.0 in /usr/local/lib/python3.9/dist-packages (from -r cryptoadvance.specter-2.0.0/requirements.txt (line 27)) (1.0.0)
Requirement already satisfied: certifi==2022.12.7 in /usr/local/lib/python3.9/dist-packages (from -r cryptoadvance.specter-2.0.0/requirements.txt (line 32)) (2022.12.7)
Requirement already satisfied: cffi==1.15.1 in /usr/local/lib/python3.9/dist-packages (from -r cryptoadvance.specter-2.0.0/requirements.txt (line 38)) (1.15.1)
Requirement already satisfied: chardet==3.0.4 in /usr/local/lib/python3.9/dist-packages (from -r cryptoadvance.specter-2.0.0/requirements.txt (line 104)) (3.0.4)
Requirement already satisfied: charset-normalizer==2.0.12 in /usr/local/lib/python3.9/dist-packages (from -r cryptoadvance.specter-2.0.0/requirements.txt (line 108)) (2.0.12)
Requirement already satisfied: click==8.1.1 in /usr/local/lib/python3.9/dist-packages (from -r cryptoadvance.specter-2.0.0/requirements.txt (line 112)) (8.1.1)
Requirement already satisfied: cryptoadvance-liquidissuer==0.2.4 in /usr/local/lib/python3.9/dist-packages (from -r cryptoadvance.specter-2.0.0/requirements.txt (line 118)) (0.2.4)
ERROR: Ignored the following versions that require a different python version: 0.3.3 Requires-Python >=3.10; 0.3.6 Requires-Python >=3.10; 0.4.0 Requires-Python >=3.10; 0.4.1 Requires-Python >=3.10; 0.4.2 Requires-Python >=3.10; 0.5.0 Requires-Python >=3.10; 0.6.0 Requires-Python >=3.10; 0.6.1 Requires-Python >=3.10; 0.6.2 Requires-Python >=3.10; 0.6.3 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement cryptoadvance-spectrum==0.6.2 (from versions: 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.3.0, 0.3.1)
ERROR: No matching distribution found for cryptoadvance-spectrum==0.6.2`

**Comment by k9ert** [comment]
Probably: Please check your python version. You need >= 3.10 ?!

**Comment by BTCBellyButton** [comment]
After updating python to 3.11.2:

```
      x86_64-linux-gnu-gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=590 -DPSUTIL_LINUX=1 -I/usr/include/python3.11 -c psutil/_psutil_common.c -o build/temp.linux-x86_64-cpython-311/psutil/_psutil_common.o
      psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory
          9 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of psutil
  Moving to /home/go/.local/lib/python3.11/site-packages/psutil-5.9.4.dist-info/
   from /home/go/.local/lib/python3.11/site-packages/~sutil-5.9.4.dist-info
  Moving to /home/go/.local/lib/python3.11/site-packages/psutil/
   from /home/go/.local/lib/python3.11/site-packages/~sutil
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> psutil

note: This is an issue with the package mentioned above, not pip.

```

**Comment by sanyangGitHub** [comment]
> Probably: Please check your python version. You need >= 3.10 ?!

Indeed. Python 3.10 was installed but not defined as default ! 
Thanks !
